name: gcc
version: '13.1.0'
sources:
  - url: https://ftp.gnu.org/gnu/gcc/gcc-11.1.0/gcc-13.1.0.tar.gz
dependencies:
  - mpc
  - mpfr
  - gmp
patches:
  - gcc-13.1.0.patch
set_cflags_sysroot: false
configure:
  - cp $PKGDIR/xelix.h gcc/config/
  - rm -r build || true
  - mkdir build
  - cd build && CPPFLAGS="$CPPFLAGS -DHAVE_SYS_WAIT_H -DHAVE_SYS_RESOURCE_H -DHAVE_DECL_SBRK -DHAVE_DECL_STRSIGNAL -D__int64_t_defined" ../configure
    --host=i786-pc-xelix
    --target=i786-pc-xelix
    --disable-shared
    --enable-static
    --prefix=/usr
    --sysconfdir=/etc
    --libdir=/usr/lib
    --libexecdir=/usr/lib
    --mandir=/usr/share/man
    --infodir=/usr/share/info
    --enable-languages=c,c++
    --with-sysroot=$DESTDIR
    --with-gmp=$DESTDIR/usr
    --with-mpfr=$DESTDIR/usr
    --with-mpc=$DESTDIR/usr
make:
  - CPPFLAGS="$CPPFLAGS -DHAVE_SYS_WAIT_H -DHAVE_SYS_RESOURCE_H -DHAVE_DECL_SBRK -DHAVE_DECL_STRSIGNAL -D__int64_t_defined" make -C build all-gcc
  - CPPFLAGS="$CPPFLAGS -DHAVE_SYS_WAIT_H -DHAVE_SYS_RESOURCE_H -DHAVE_DECL_SBRK -DHAVE_DECL_STRSIGNAL -D__int64_t_defined" make -C build all-target-libgcc
#  - CPPFLAGS="$CPPFLAGS -DHAVE_SYS_WAIT_H -DHAVE_SYS_RESOURCE_H -DHAVE_DECL_SBRK -DHAVE_DECL_STRSIGNAL -D__int64_t_defined" make -C build all-target-libstdc++-v3 || true
install:
  - make -C build install-gcc
  - make -C build install-target-libgcc
#  - make -C build install-target-libstdc++-v3 || true
