name: gmp
version: '6.2.0'
sources:
  - url: https://gmplib.org/download/gmp/gmp-6.2.0.tar.xz
patch_skip_path: 0
patches:
  - gmp-6.2.0.patch
configure:
  - CC=i786-pc-xelix-gcc ./configure
    --host=i786-pc-xelix
    --target=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --disable-shared
make:
  - make
install:
  - make install
  - rm $DESTDIR/usr/lib/libgmp.la
