name: gmp
version: '6.1.2'
sources:
  - url: https://gmplib.org/download/gmp/gmp-6.1.2.tar.xz
patches:
  - gmp-6.1.2.patch
configure:
  - CC=i786-pc-xelix-gcc ./configure
    --host=i786-pc-xelix
    --target=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --disable-shared
make:
  - make
install:
  - make install
  - rm $DESTDIR/usr/lib/libgmp.la
