name: wget
version: 1.20.3
sources:
  - url: https://ftp.gnu.org/gnu/wget/wget-1.20.3.tar.gz
dependencies:
  - zlib
  - pcre2
  - openssl
patches:
  - wget-1.20.3.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --with-ssl=openssl
    --disable-threads
    --without-libpsl

  # Needs to be applied after configure
  - patch -p1 < $PKGDIR/wget-1.20.3-two.patch
make:
  - make
install:
  - make install
