name: pcre2
version: 10.32
sources:
  - url: https://github.com/PCRE2Project/pcre2/releases/download/pcre2-10.32/pcre2-10.32.tar.bz2
patches:
  - pcre2-10.32.patch
configure:
  - ./configure --host=i786-pc-xelix --prefix=/usr --sysconfdir=/etc
make:
  - make
install:
  - make install
  - rm $DESTDIR/usr/lib/libpcre2-8.la
  - rm $DESTDIR/usr/lib/libpcre2-posix.la
