name: darkhttpd
version: 1.13
sources:
  - url: https://github.com/emikulic/darkhttpd/archive/refs/tags/v1.13.tar.gz
patches:
  - darkhttpd-1.13.patch
make:
  - CC=i786-pc-xelix-gcc CFLAGS="-O3 -DNO_IPV6" make
install:
  - install -D darkhttpd $DESTDIR/usr/bin/
