name: darkhttpd
version: 1.12
sources:
  - url: https://unix4lyfe.org/darkhttpd/darkhttpd-1.12.tar.bz2
patches:
  - darkhttpd-1.12.patch
make:
  - CC=i786-pc-xelix-gcc CFLAGS="-O3 -DNO_IPV6" make
install:
  - install -D darkhttpd $DESTDIR/usr/bin/
