site_name: Xelix documentation
repo_name: 'lutoma/xelix'
repo_url: 'https://github.com/lutoma/xelix'
site_url: 'https://xelix.org'
edit_uri: edit/main/docs/
markdown_extensions:
  - smarty
  - tables
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.inlinehilite
  - toc:
      permalink: true
plugins:
  - search
  - mermaid2
theme:
  name: 'material'
  logo: 'images/92014.svg'
  features:
# breaks mermaid2
#     - navigation.instant
     - navigation.tracking
#     - navigation.tabs
     - navigation.sections
     - navigation.top
#     - toc.integrate

# breaks mermaid2
#  palette:
#    - media: "(prefers-color-scheme: light)"
#      scheme: default
#      primary: indigo
#      toggle:
#        icon: material/toggle-switch-off-outline
#        name: Switch to dark mode
#    - media: "(prefers-color-scheme: dark)"
#      scheme: slate
#      primary: indigo
#      accent: deep orange
#      toggle:
#        icon: material/toggle-switch
#        name: Switch to light mode

nav:
- Home: 'index.md'

- 'Userland':
  - 'xelix-utils.md'
  - 'gfxcompd.md'
- 'Kernel':
  - 'compiling.md'
  - boot.md
  - mem.md
  - int.md
  - tasks.md
  - fs.md
  - net.md
- 'Reference':
  - lib.md
