site_name: Xelix documentation
repo_name: 'lutoma/xelix'
repo_url: 'https://github.com/lutoma/xelix'
site_url: 'https://xelix.org'
edit_uri: edit/main/docs/
markdown_extensions:
  - smarty
  - tables
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - toc:
      permalink: true
plugins:
  - search
theme:
  name: 'material'
  logo: 'images/92014.svg'
  features:
     - navigation.instant
     - navigation.tracking
#     - navigation.tabs
     - navigation.sections
     - navigation.top
nav:
- Home: 'index.md'

- 'Userland':
  - 'xelix-utils.md'
  - 'gfxcompd.md'
- 'Kernel':
  - 'compiling.md'
  - boot.md
  - mem.md
  - int.md
  - tasks.md
  - fs.md
  - net.md
- 'Reference':
  - lib.md
