name: pixman
version: '0.38.4'
sources:
  - url: https://cairographics.org/releases/pixman-0.38.4.tar.gz
patch_skip_path: 0
patches:
  - pixman.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --localstatedir=/var
make:
  - make
install:
  - make DESTDIR=$DESTDIR install
  - rm $DESTDIR/usr/lib/libpixman-1.la
