name: dialog
version: 1.3-20191210
sources:
  - url: https://invisible-island.net/datafiles/release/dialog.tar.gz
dependencies:
  - ncurses
patches:
  - dialog-1.3-20191210.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --disable-shared
    --enable-static
    --prefix=/usr
    --sysconfdir=/etc
make:
  - make
install:
  - make DESTDIR=$DESTDIR install
