name: libtextstyle
version: '0.8'
sources:
  - url: https://alpha.gnu.org/gnu/gettext/libtextstyle-0.8.tar.gz
dependencies:
  - ncurses
patch_skip_path: 0
patches:
  - libtextstyle.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
make:
  - make
install:
  - make install
  - rm $DESTDIR/usr/lib/libtextstyle.la
