name: coreutils
version: '8.32'
sources:
  - url: https://ftp.gnu.org/gnu/coreutils/coreutils-8.32.tar.xz
dependencies:
  - libiconv
  - openssl
  - libiconv
  - gmp
patches:
  - coreutils-8.32.patch
configure:
  - autoreconf
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --disable-threads
    --disable-acl
    --disable-xattr
    --disable-largefile
    --enable-no-install-program=arch,coreutils,dmesg,mknod
    --with-openssl

  # Needs to be applied after configure
  - patch -p1 < $PKGDIR/coreutils-8.32-patch-two.patch
make:
  - make
install:
  - make install
