name: xelix-utils
version: 0.1.0
sources:
  - dir: src
dependencies:
  - font-fira-code
  - gfxcompd
  - flac
  - freetype
  - libpng
make:
  - CFLAGS="$CFLAGS -I$DESTDIR/usr/include" make
install:
  - make install
