name: libexpat
version: '2.2.9'
sources:
  - url: https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.xz
patch_skip_path: 0
patches:
  - libexpat.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
make:
  - make
install:
  - make DESTDIR=$DESTDIR install
  - rm $DESTDIR/usr/lib/libexpat.la
