name: ffmpeg
version: 4.4
sources:
  - url: https://ffmpeg.org/releases/ffmpeg-4.4.tar.xz
dependencies:
  - flac
patches:
  - ffmpeg.patch
patch_skip_path: 0
configure:
  - cp $PKGDIR/xelixsnd.c libavdevice/
  - cp $PKGDIR/xelixsnd.h libavdevice/
  - cp $PKGDIR/xelixsnd_enc.c libavdevice/
  - CFLAGS="-D__have_long64=0 -D__int64_t_defined" ./configure
    --arch=x86
    --target-os=xelix
    --cross-prefix=i786-pc-xelix-
    --prefix=/usr
    --disable-shared
    --disable-network
make:
  - make
install:
  - make install
