name: newlib
version: 3.2.0
sources:
  - url: http://sourceware.org/pub/newlib/newlib-3.2.0.tar.gz
patches:
  - newlib-3.2.0.patch
set_cflags_sysroot: false
set_cflags_include: false
set_ldflags_libpath: false
configure:
  - cp -r $PKGDIR/xelix newlib/libc/sys/

  - cd newlib/libc/sys/xelix/ && aclocal-1.11 -I ../../../ -I ../../../../
  - cd newlib/libc/sys/xelix/ && autoconf-2.69
  - cd newlib/libc/sys/xelix/ && automake-1.11 --cygnus Makefile

  - cd newlib/libc/sys/ && aclocal-1.11 -I ../.. -I ../../..
  - cd newlib/libc/sys/ && autoconf-2.69
  - cd newlib/libc/sys/ && automake-1.11 --cygnus Makefile

  - ./configure
    --target=i786-pc-xelix
    --prefix=/usr
    --exec-prefix=/usr
    --sysconfdir=/etc
    --enable-newlib-mb
    --enable-newlib-iconv
    --enable-newlib-io-c99-formats
    --enable-newlib-io-long-long
    --enable-newlib-io-long-double
make:
  - make
install:
  # Work around newlib build setup issues
  - make DESTDIR=/tmp/newlib-install install
  - cp -r /tmp/newlib-install/usr/i786-pc-xelix/* $DESTDIR/usr/
  - cp i786-pc-xelix/newlib/libc/sys/xelix/crti.o i786-pc-xelix/newlib/libc/sys/xelix/crtn.o $DESTDIR/usr/lib/
  - rm -r /tmp/newlib-install

  # Some GNU packages expect xlocale.h to exist
  - ln -s locale.h $DESTDIR/usr/include/xlocale.h || true
