name: libxml2
version: 2.9.9
sources:
  - url: ftp://xmlsoft.org/libxml2/libxml2-2.9.9.tar.gz
dependencies:
  - zlib
  - xz
patches:
  - libxml2-2.9.9.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --without-threads
    --without-http
    --without-python
make:
  - make
install:
  - make install
  - rm $DESTDIR/usr/lib/libxml2.la
