name: bash
version: 5.0
sources:
  - url: https://ftp.gnu.org/gnu/bash/bash-5.0.tar.gz
patches:
  - bash-5.0.patch
configure:
# Multiple definitions needed due to confliction definitions in termcap/libreadline
  - LDFLAGS="-Wl,--allow-multiple-definition" ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --without-bash-malloc
    --disable-job-control
make:
  - make
install:
  - make DESTDIR=$DESTDIR install
