name: libiconv
version: '1.16'
sources:
  - url: https://ftp.gnu.org/pub/gnu/libiconv/libiconv-1.16.tar.gz
patch_skip_path: 0
patches:
  - libiconv.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
make:
  - make
install:
  - make DESTDIR=$DESTDIR install
  - rm $DESTDIR/usr/lib/libcharset.la
  - rm $DESTDIR/usr/lib/libiconv.la
