name: cairo
version: '1.16.0'
sources:
  - url: https://www.cairographics.org/releases/cairo-1.16.0.tar.xz
dependencies:
  - zlib
  - libpng
  - freetype
  - fontconfig
  - pixman
patch_skip_path: 0
patches:
  - cairo.patch
configure:
  - CFLAGS="$CFLAGS -DCAIRO_NO_MUTEX=1 -g -I$DESTDIR/usr/include"
    LDFLAGS="$LDFLAGS -I$DESTDIR/usr/lib -g"
    ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --localstatedir=/var
    --disable-xcb
    --disable-xcb-shm
    --disable-xlib
    --disable-xlib-xrender
    --disable-gobject
    --disable-fc

  - echo -e 'all:\n\ttrue\ninstall:\n\ttrue' > test/Makefile
  - echo -e 'all:\n\ttrue\ninstall:\n\ttrue' > perf/Makefile

make:
  - make
install:
  - make DESTDIR=$DESTDIR install
  - rm $DESTDIR/usr/lib/libcairo.la
  - rm $DESTDIR/usr/lib/libcairo-script-interpreter.la
