name: libedit
version: 20191231-3.1
sources:
  - url: https://thrysoee.dk/editline/libedit-20191231-3.1.tar.gz
dependencies:
  - ncurses
patches:
  - libedit-20191231-3.1.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --disable-shared
    --disable-widec
make:
  - make
install:
  - make install
  - rm $DESTDIR/usr/lib/libedit.la
