name: mpc
version: '1.2.0'
sources:
  - url: https://ftp.gnu.org/gnu/mpc/mpc-1.2.0.tar.gz
dependencies:
  - gmp
  - mpfr
patch_skip_path: 0
patches:
  - mpc-1.2.0.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --disable-shared
    --with-gmp-include=$DESTDIR/usr/include
    --with-gmp-lib=$DESTDIR/usr/lib
    --with-mpfr-include=$DESTDIR/usr/include
    --with-mpfr-lib=$DESTDIR/usr/lib
make:
  - make
install:
  - make install
  - rm $DESTDIR/usr/lib/libmpc.la
