name: vim
version: 8.1
sources:
  - url: ftp://ftp.vim.org/pub/vim/unix/vim-8.1.tar.bz2
dependencies:
  - ncurses
configure:
  - ac_cv_sizeof_int=4
    vim_cv_getcwd_broken=no
    vim_cv_memmove_handles_overlap=yes
    vim_cv_stat_ignores_slash=yes
    vim_cv_tgetent=zero
    vim_cv_terminfo=yes
    vim_cv_toupper_broken=no
    vim_cv_tty_group=world
    ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --with-tlib=ncurses
  - cd src && sh osdef.sh
make:
  - make
install:
  - make install
  - ln -s vim $DESTDIR/usr/bin/vi
