name: mpfr
version: 4.1.0
sources:
  - url: https://www.mpfr.org/mpfr-current/mpfr-4.1.0.tar.xz
dependencies:
  - gmp
patch_skip_path: 0
patches:
  - mpfr-4.1.0.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --disable-shared
    --with-gmp-include=$DESTDIR/usr/include
    --with-gmp-lib=$DESTDIR/usr/lib
make:
  - make
install:
  - make install
  - rm $DESTDIR/usr/lib/libmpfr.la
