name: binutils
version: 2.31.1
sources:
  - url: https://ftp.gnu.org/gnu/binutils/binutils-2.31.1.tar.gz
patch_skip_path: 0
patches:
  - binutils-2.31.1.patch
configure:
  - find . -name "config.cache" -delete
  - cp $PKGDIR/elf_i386_xelix.sh ld/emulparams/
  - cd ld && aclocal
  - cd ld && automake
  - autoreconf
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
    --disable-werror
    --disable-plugins
    --disable-nls
make:
  - make
install:
  - make install
