name: libarchive
version: 3.7.2
dependencies:
  - libxml2
  - openssl
  - bzip2
  - zlib
  - libiconv
  - xz
sources:
  - url: https://github.com/libarchive/libarchive/releases/download/v3.7.2/libarchive-3.7.2.tar.xz
patches:
  - libarchive-3.7.2.patch
patch_skip_path: 0
configure:
  - LIBS="-lxml2 -lz -llzma -lm" ./configure --host=i786-pc-xelix --prefix=/usr --sysconfdir=/etc
make:
  - make
install:
  - make install
