name: tar
version: '1.32'
sources:
  - url: https://ftp.gnu.org/gnu/tar/tar-1.32.tar.xz
patches:
  - tar-1.32.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
make:
  - make
install:
  - make install
