name: grep
version: 3.1
sources:
  - url: https://ftp.gnu.org/gnu/grep/grep-3.1.tar.xz
patches:
  - grep-3.1.patch
configure:
  - ./configure
    --host=i786-pc-xelix
    --prefix=/usr
    --sysconfdir=/etc
make:
  - make
install:
  # Install segfaults because it tries to run the cross-compiled binary… still installs though
  - make install || false
