name: gzip
version: 1.9
sources:
  - url: https://ftp.gnu.org/gnu/gzip/gzip-1.9.tar.xz
patches:
  - gzip-1.9.patch
configure:
  - ./configure --host=i786-pc-xelix --prefix=/usr --sysconfdir=/etc
make:
  - make
install:
  - make install
