name: Build docs

on:
  push:
    branches:
      - main

    paths:
      - 'docs/**'
      - 'mkdocs.yml'

defaults:
  run:
    working-directory: docs

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get install -y lftp

      - name: Set up Python 3.10.0
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.0

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.12

      - name: Install Python dependencies
        run: poetry install -n

      - name: Run mkdocs
        run: poetry run mkdocs build -f ../mkdocs.yml

      - name: Push site
        run: lftp sftp://ws309@w2.fnordserver.net --password ${{ secrets.SFTP_PASSWORD }} -e "mirror --reverse --delete ../site httpdocs; bye"
