name: Kernel binary build

on:
  push:
    branches:
      - main

    paths:
      - 'src/**'
      - 'ext/**'
      - 'Makefile.static'
      - 'configure'
      - '.github/workflows/kernel.yml'

jobs:
  kernel:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lutoma/xelix/toolchain:latest
      options: --user 1000

    steps:
      - name: Adjust dir permissions
        run: 'sudo chown dev: /src'

      - name: Import signing key
        run: 'echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import'

      - name: Download PKGBUILD
        run: 'wget -q https://raw.githubusercontent.com/lutoma/xelix/main/land/xelix-kernel/PKGBUILD'

      - name: Run makepkg
        run:  'makepkg -Ad --sign'

      - name: Adjust package name
        run: 'rename x86_64 i786 *'

      - name: 'Create package directory'
        run: 'mkdir kernel-pkg'

      - name: 'Move stuff around'
        run: 'mv *.pkg.* kernel-pkg'

      - name: Upload package as artifact
        uses: actions/upload-artifact@v3
        with:
          name: kernel-pkg
          path: kernel-pkg
