name: Build nightly image

on:
  workflow_dispatch:
  schedule:
    - cron: '35 4 * * *'

jobs:
  image:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/lutoma/xelix/toolchain:latest
      options: --privileged

    steps:
      - name: Download build script
        run: 'wget -q https://raw.githubusercontent.com/lutoma/xelix/main/util/build-image.sh'

      - name: Build image
        run: bash build-image.sh xelix-nightly.img

      - name: Import signing key
        run: 'echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import'

      - name: Sign image
        run: gpg --detach-sign --armor xelix-nightly.img

      - name: Import SSH key
        run: 'echo "${{ secrets.SSH_KEY }}" > /root/.ssh/id_ed25519 && chmod 600 /root/.ssh/id_ed25519'

      - name: Upload to server
        run: rsync xelix-nightly.img xelix-nightly.img.asc repoupdate@pkgs.xelix.org:/var/www/pkgs.xelix.org

